version: '3.4'

services:
  web:
    build: .
    command: sh /start.sh
    volumes:
      - static_volume:/pat/pat_test/static
    expose:
      - 8000
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=pat_test.settings.deploy
      - SQL_DATABASE=web
      - SQL_ENGINE=django.db.backends.postgresql_psycopg2
      - SQL_HOST=db
    depends_on:
      - db

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_volume:/pat/pat_test/static

  db:
    image: postgres:11.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pwd_admin
      - POSTGRES_DB=web
      
volumes:
  static_volume:
  postgres_data:
