# Generated by Django 2.2.4 on 2019-08-05 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('test_engineer', models.CharField(max_length=100)),
                ('pending', models.BooleanField()),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAT.Tools')),
            ],
        ),
    ]
