# Generated by Django 2.2.4 on 2019-08-05 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PAT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='revision',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PAT.Tool'),
        ),
        migrations.DeleteModel(
            name='Tools',
        ),
    ]
