# Generated by Django 2.2.4 on 2019-08-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAT', '0003_auto_20190805_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revision',
            name='pending',
        ),
        migrations.AddField(
            model_name='tool',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
