# Generated by Django 2.2.4 on 2019-08-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAT', '0004_auto_20190805_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='comment',
            field=models.TextField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='revision',
            name='earth',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revision',
            name='function_check',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revision',
            name='insulation',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revision',
            name='leakage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revision',
            name='visual_check',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
