# Generated by Django 2.2.4 on 2019-08-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAT', '0005_auto_20190805_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='_class',
            field=models.IntegerField(default=1, verbose_name='class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revision',
            name='location',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
