# Generated by Django 2.2.4 on 2019-08-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAT', '0006_auto_20190805_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revision',
            old_name='_class',
            new_name='classID',
        ),
        migrations.AlterField(
            model_name='tool',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
