# Generated by Django 2.2.4 on 2019-08-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAT', '0007_auto_20190806_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='function_check',
            field=models.IntegerField(choices=[(1, 'Pass'), (2, 'Fail')]),
        ),
        migrations.AlterField(
            model_name='revision',
            name='visual_check',
            field=models.IntegerField(choices=[(1, 'Pass'), (2, 'Fail')]),
        ),
    ]
