# Generated by Django 2.2.4 on 2019-09-08 16:02

from django.db import migrations, models
from django.db import transaction

def move_location(apps, schema_editor):
    Tool = apps.get_model("PAT", "Tool")
    Revision = apps.get_model("PAT", "Revision")

    for tool in Tool.objects.all():
        with transaction.atomic():
            rl =Revision.objects.filter(tool=tool)
            if rl:
                tool.location = rl.latest('id').location
                tool.save()

class Migration(migrations.Migration):

    dependencies = [
        ('PAT', '0008_auto_20190806_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='location',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.RunPython(move_location, atomic=False),
        migrations.RemoveField(
            model_name='revision',
            name='location',
        ),
    ]
