# Generated by Django 2.2.4 on 2019-09-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PAT', '0009_auto_20190908_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='earth',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='revision',
            name='insulation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='revision',
            name='leakage',
            field=models.CharField(max_length=100),
        ),
    ]
