# Generated by Django 2.2.4 on 2019-09-14 17:48

from django.db import migrations, models
from django.db import transaction

def move_class(apps, schema_editor):
    Tool = apps.get_model("PAT", "Tool")
    Revision = apps.get_model("PAT", "Revision")

    for tool in Tool.objects.all():
        with transaction.atomic():
            rl =Revision.objects.filter(tool=tool)
            if rl:
                tool.classID = rl.latest('id').classID
                tool.save()


class Migration(migrations.Migration):

    dependencies = [
        ('PAT', '0010_auto_20190908_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='classID',
            field=models.IntegerField(default=2, verbose_name='class'),
            preserve_default=False,
        ),
        migrations.RunPython(move_class, atomic=False),
        migrations.RemoveField(
            model_name='revision',
            name='classID',
        ),
    ]
